from schema import METRICS, DIMENSIONS, TIME_GRANULARITIES


SUPPORTED_OPERATIONS = {
    "total",
    "highest",
    "lowest",
    "compare",
}


def validate_query(query):
    """
    Validate the structured query generated by the AI agent.

    The agent produces semantic information only.
    Raw SQL is not generated here.
    """

    errors = []

    if not isinstance(query, dict):
        return {
            "valid": False,
            "errors": ["Agent output must be a dictionary."]
        }

    metric = query.get("metric")
    dimension = query.get("dimension")
    time_granularity = query.get("time_granularity")
    operation = query.get("operation")

    # Validate metric
    if metric is None:
        errors.append("No supported metric was identified.")
    elif metric not in METRICS:
        errors.append(f"Unsupported metric: '{metric}'.")

    # Validate normal business dimension
    if dimension is not None and dimension not in DIMENSIONS:
        errors.append(f"Unsupported dimension: '{dimension}'.")

    # Validate time granularity
    if (
        time_granularity is not None
        and time_granularity not in TIME_GRANULARITIES
    ):
        errors.append(
            f"Unsupported time granularity: '{time_granularity}'."
        )

    # A time-series query should not use Year as both
    # a normal dimension and a time granularity.
    if (
        dimension == "Year"
        and time_granularity is not None
    ):
        errors.append(
            "Year cannot be used as both a dimension "
            "and a time granularity."
        )

    # Validate operation
    if operation is not None and operation not in SUPPORTED_OPERATIONS:
        errors.append(f"Unsupported operation: '{operation}'.")

    # Validate filters
    filters = query.get("filters", {})

    if not isinstance(filters, dict):
        errors.append("Filters must be a dictionary.")
    else:
        year = filters.get("Year")

        if year is not None:
            if not isinstance(year, int) or isinstance(year, bool):
                errors.append("Year filter must be an integer.")
            elif year < 1900 or year > 2100:
                errors.append(
                    "Year filter is outside the supported range."
                )

    # Validate ambiguity structure
    ambiguity = query.get("ambiguity", {})

    if not isinstance(ambiguity, dict):
        errors.append(
            "Ambiguity information must be a dictionary."
        )

    return {
        "valid": len(errors) == 0,
        "errors": errors,
    }