SELECT DISTINCT
    CAST(ORDER_DATE AS DATE) AS DATE_KEY,

    EXTRACT(DAY FROM ORDER_DATE) AS DAY,
    EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,
    EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
    EXTRACT(QUARTER FROM ORDER_DATE) AS QUARTER,

    WEEKNUM AS WEEK_NUMBER,

    CASE
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 1 THEN 'January'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 2 THEN 'February'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 3 THEN 'March'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 4 THEN 'April'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 5 THEN 'May'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 6 THEN 'June'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 7 THEN 'July'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 8 THEN 'August'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 9 THEN 'September'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 10 THEN 'October'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 11 THEN 'November'
        WHEN EXTRACT(MONTH FROM ORDER_DATE) = 12 THEN 'December'
    END AS MONTH_NAME

FROM {{ ref('int_sales_enriched') }}
WHERE ORDER_DATE IS NOT NULL