name: 'metricmind_dbt'
version: '1.0.0'
config-version: 2

profile: 'metricmind_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  metricmind_dbt:

    staging:
      +materialized: view
      +schema: STAGING

    intermediate:
      +materialized: table
      +schema: INTERMEDIATE

    marts:
      +materialized: table
      +schema: MART